parameters:
  app.public_controller_ids: [ ]
  app.admin_controller_ids: [ ]

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    LPTS\Application\Contract\PublicControllerInterface:
      public: true
      tags: [ 'app.public.controller' ]

    LPTS\Application\Contract\AdminControllerInterface:
      public: true
      tags: [ 'app.admin.controller' ]

  LPTS\:
    resource: '../src/*'
    exclude: '../src/{index.php}'
